version: '3.8'

services:
  api-dev:
    container_name: rest-api-dev
    restart: unless-stopped
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - ./api/.env
    # environment:
    #   - MONGODB_URL=mongodb://mongo:27017/restAPI
    volumes:
      - ./api/src:/app/src
    networks:
      - devat

  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - devat

volumes:
  mongodb:

networks:
  devat: