version: '3.8'

services:
  api-prod:
    container_name: rest-api-prod
    restart: unless-stopped
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    env_file:
      - ./api/.env
    # environment:
    #   - MONGODB_URL=mongodb://mongo:27017/restAPI
    depends_on:
      - mongo
      - redis
    networks:
      - devat

  client-prod:
    container_name: client-prod
    restart: unless-stopped
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    depends_on:
      - api-prod
    networks:
      - devat

  mongo:
    image: mongo:5.0.5
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - devat

  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    networks:
      - devat

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-prod
      - client-prod
    networks:
      - devat

volumes:
  mongodb:
  redis:

networks:
  devat: